// src/lib/artifact/extractor.ts — Extract artifact blocks from AI messages

export interface ArtifactFile {
  path: string;
  content: string;
}

export interface ArtifactBlock {
  id: string;
  code: string;
  title?: string;
  files?: ArtifactFile[];
}

const ARTIFACT_START = '<!-- lyra-artifact';
const ARTIFACT_END = '<!-- /lyra-artifact -->';
const FILE_START = '<!-- lyra-file';
const FILE_END = '<!-- /lyra-file -->';

/**
 * Parse multi-file markers within an artifact block.
 * If no lyra-file markers found, treat entire code as single index.html.
 */
function parseFiles(code: string): ArtifactFile[] {
  const files: ArtifactFile[] = [];
  let hasFileMarkers = false;
  let searchFrom = 0;

  while (searchFrom < code.length) {
    const startIdx = code.indexOf(FILE_START, searchFrom);
    if (startIdx === -1) break;

    const startTagEnd = code.indexOf('-->', startIdx);
    if (startTagEnd === -1) break;
    const startTag = code.substring(startIdx, startTagEnd + 3);

    const pathMatch = startTag.match(/path=["']([^"']*)["']/);
    const filePath = pathMatch?.[1] || `index-${files.length}.html`;

    const contentStart = startTagEnd + 3;
    const endIdx = code.indexOf(FILE_END, contentStart);
    if (endIdx === -1) break;

    const fileContent = code.substring(contentStart, endIdx).trim();
    if (fileContent.length > 0) {
      files.push({ path: filePath, content: fileContent });
      hasFileMarkers = true;
    }

    searchFrom = endIdx + FILE_END.length;
  }

  // If no file markers found, treat entire code as single HTML file
  if (!hasFileMarkers) {
    return [{ path: 'index.html', content: code }];
  }

  return files;
}

/**
 * Extract all artifact blocks from a message string.
 */
export function extractArtifacts(content: string): ArtifactBlock[] {
  const artifacts: ArtifactBlock[] = [];
  let searchFrom = 0;

  while (searchFrom < content.length) {
    const startIdx = content.indexOf(ARTIFACT_START, searchFrom);
    if (startIdx === -1) break;

    const startTagEnd = content.indexOf('-->', startIdx);
    if (startTagEnd === -1) break;
    const startTagFull = content.substring(startIdx, startTagEnd + 3);

    const titleMatch = startTagFull.match(/title="([^"]*)"/);
    const title = titleMatch?.[1] || undefined;

    const codeStart = startTagEnd + 3;
    const endIdx = content.indexOf(ARTIFACT_END, codeStart);
    if (endIdx === -1) break;

    const code = content.substring(codeStart, endIdx).trim();
    if (code.length > 0) {
      const files = parseFiles(code);
      artifacts.push({
        id: `artifact-${artifacts.length}-${Date.now()}`,
        code,
        title,
        files,
      });
    }

    searchFrom = endIdx + ARTIFACT_END.length;
  }

  return artifacts;
}

/**
 * Check if a message contains at least one artifact block (complete).
 */
export function hasArtifact(content: string): boolean {
  return content.includes(ARTIFACT_START) && content.includes(ARTIFACT_END);
}

/**
 * Check if message has a start marker but NO end marker (incomplete/partial artifact).
 */
export function hasPartialArtifact(content: string): boolean {
  return content.includes(ARTIFACT_START) && !content.includes(ARTIFACT_END);
}

/**
 * Remove artifact blocks from message content.
 * Also handles partial artifacts (start marker but no end marker).
 */
export function stripArtifacts(content: string): string {
  let result = content;
  let idx = 0;

  while (true) {
    const startIdx = result.indexOf(ARTIFACT_START, idx);
    if (startIdx === -1) break;

    const endIdx = result.indexOf(ARTIFACT_END, startIdx);
    if (endIdx === -1) {
      // Partial artifact — remove from start marker to end of content
      result = result.substring(0, startIdx);
      break;
    }

    const before = result.substring(0, startIdx);
    const after = result.substring(endIdx + ARTIFACT_END.length);
    result = before + after;
    idx = before.length;
  }

  return result.trim();
}


/**
 * Prepare HTML for iframe preview by directly injecting CSS and JS inline.
 * This completely avoids CORS issues, Blob URL limits, and iframe origin restrictions.
 */
export function buildPreviewHtml(files: ArtifactFile[]): string {
  let html = files.find(f => f.path === 'index.html')?.content || '';

  if (!html) {
    const htmlFile = files.find(f => f.path.endsWith('.html'));
    html = htmlFile?.content || files[0]?.content || '';
  }

  // Ensure it's a full HTML document
  if (!html.trim().toLowerCase().startsWith('<!doctype') && !html.trim().toLowerCase().startsWith('<html')) {
    html = `<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>body{margin:0;font-family:system-ui,sans-serif;}</style>
</head>
<body>${html}</body>
</html>`;
  }

  // 1. Remove all external <link> CSS generated by AI to avoid 404s
  html = html.replace(/<link[^>]*rel=["']stylesheet["'][^>]*>/gi, '');
  
  // 2. Remove all external <script src="..."> generated by AI to avoid 404s
  html = html.replace(/<script[^>]*src=["'][^"']*["'][^>]*>\s*<\/script>/gi, '');

  // 3. Gather all CSS content
  const cssFiles = files.filter(f => f.path.endsWith('.css'));
  let combinedCss = '';
  for (const css of cssFiles) {
    combinedCss += `\n/* File: ${css.path} */\n${css.content}\n`;
  }

  // 4. Gather all JS content
  const jsFiles = files.filter(f => f.path.endsWith('.js'));
  let combinedJs = '';
  for (const js of jsFiles) {
    combinedJs += `\n// File: ${js.path}\n${js.content}\n`;
  }

  // 5. Detect CSS pointer-events issues
  const cssCheckStyle = `\n/* Lyra CSS Check - highlight elements blocked by pointer-events:none */\n[style*="pointer-events: none"] button,\n[style*="pointer-events: none"] a,\n[style*="pointer-events: none"] [onclick],\n[style*="pointer-events: none"] [role="button"] {\n  outline: 3px solid #ef4444 !important;\n  outline-offset: 2px !important;\n}\n[style*="pointer-events: none"] button::after,\n[style*="pointer-events: none"] a::after {\n  content: " BLOCKED by pointer-events:none on parent!" !important;\n  position: absolute !important;\n  bottom: 100% !important;\n  left: 0 !important;\n  background: #ef4444 !important;\n  color: white !important;\n  font: 10px/1.2 sans-serif !important;\n  padding: 2px 6px !important;\n  border-radius: 4px !important;\n  white-space: nowrap !important;\n  z-index: 99999 !important;\n}\n`;

  // 6. Setup Global Error Catcher
  const errorCatcherScript = `
// --- Lyra Error Catcher ---
window.__LYRA_ERROR_CATCHER__ = true;
window.addEventListener('error', function(e) {
  console.error('[Lyra Error]', e.error ? e.error.message : e.message);
  var msg = (e.error ? e.error.message : e.message) || 'Unknown error';
  var badge = document.getElementById('lyra-error-badge');
  if (!badge) {
    badge = document.createElement('div');
    badge.id = 'lyra-error-badge';
    badge.style.cssText = 'position:fixed;bottom:8px;right:8px;background:#ef4444;color:white;font:11px/1.4 system-ui,sans-serif;padding:6px 10px;border-radius:6px;z-index:99999;max-width:80%;pointer-events:auto;box-shadow:0 2px 8px rgba(0,0,0,0.3);transition:opacity 0.3s;';
    document.body.appendChild(badge);
  }
  var count = parseInt(badge.dataset.count || '0') + 1;
  badge.dataset.count = count;
  badge.textContent = '\u26A0\uFE0F ' + count + ': ' + msg;
  setTimeout(function() { if (badge) badge.style.opacity = '0.5'; }, 8000);
  try { window.parent.postMessage({ type: 'lyra-error', message: msg, count: count }, '*'); } catch(err) {}
});
window.addEventListener('unhandledrejection', function(e) {
  console.error('[Lyra Error] Unhandled Promise:', e.reason);
  var msg = (e.reason && e.reason.message) || String(e.reason) || 'Promise rejection';
  var badge = document.getElementById('lyra-error-badge');
  if (!badge) {
    badge = document.createElement('div');
    badge.id = 'lyra-error-badge';
    badge.style.cssText = 'position:fixed;bottom:8px;right:8px;background:#ef4444;color:white;font:11px/1.4 system-ui,sans-serif;padding:6px 10px;border-radius:6px;z-index:99999;max-width:80%;pointer-events:auto;box-shadow:0 2px 8px rgba(0,0,0,0.3);transition:opacity 0.3s;';
    document.body.appendChild(badge);
  }
  var count = parseInt(badge.dataset.count || '0') + 1;
  badge.dataset.count = count;
  badge.textContent = '\u26A0\uFE0F ' + count + ': ' + msg;
  try { window.parent.postMessage({ type: 'lyra-error', message: msg, count: count }, '*'); } catch(err) {}
});
// --- End Error Catcher ---
`;

  // 7. Inject everything into HTML safely
  // Inject CSS right before </head>
  if (html.includes('</head>')) {
    html = html.replace('</head>', `<style>\n${cssCheckStyle}\n${combinedCss}\n</style>\n</head>`);
  } else {
    // If no <head>, prepend it
    html = `<style>\n${cssCheckStyle}\n${combinedCss}\n</style>\n` + html;
  }

  // Inject JS right before </body> to ensure all DOM elements exist
  // We wrap combinedJs in a script tag.
  const finalJsPayload = `<script>\n${errorCatcherScript}\n${combinedJs}\n</script>`;
  if (html.includes('</body>')) {
    html = html.replace('</body>', `${finalJsPayload}\n</body>`);
  } else {
    // If no </body>, append it
    html = html + '\n' + finalJsPayload;
  }

  return html;
}
